/* Weenie - Koga Hideki (6626) */
DELETE FROM weenie WHERE class_Id = 6626;

INSERT INTO weenie (`class_Id`, `class_Name`, `type`)
VALUES (6626, 'kogahideki', 10 /* Creature_WeenieType */);

INSERT INTO `weenie_properties_string` (`object_Id`, `type`, `value`)
VALUES (6626, 001 /* NAME_STRING */, 'Koga Hideki')
     , (6626, 003 /* SEX_STRING */, 'Male')
     , (6626, 004 /* HERITAGE_GROUP_STRING */, 'Sho')
     , (6626, 005 /* TEMPLATE_STRING */, 'Master Armorer');

INSERT INTO `weenie_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (6626, 001 /* SETUP_DID */, 33554433)
     , (6626, 002 /* MOTION_TABLE_DID */, 150994945)
     , (6626, 003 /* SOUND_TABLE_DID */, 536870913)
     , (6626, 004 /* COMBAT_TABLE_DID */, 805306368)
     , (6626, 008 /* ICON_DID */, 100667446);

INSERT INTO `weenie_properties_int` (`object_Id`, `type`, `value`)
VALUES (6626, 001 /* ITEM_TYPE_INT */, 16 /* TYPE_CREATURE */)
     , (6626, 002 /* CREATURE_TYPE_INT */, 31 /* Human_CreatureType */)
     , (6626, 006 /* ITEMS_CAPACITY_INT */, -1)
     , (6626, 007 /* CONTAINERS_CAPACITY_INT */, -1)
     , (6626, 008 /* MASS_INT */, 120)
     , (6626, 016 /* ITEM_USEABLE_INT */, 32 /* USEABLE_REMOTE */)
     , (6626, 025 /* LEVEL_INT */, 53)
     , (6626, 027 /* ARMOR_TYPE_INT */, 0)
     , (6626, 093 /* PHYSICS_STATE_INT */, 6292504 /* REPORT_COLLISIONS_PS, IGNORE_COLLISIONS_PS, GRAVITY_PS, REPORT_COLLISIONS_AS_ENVIRONMENT_PS, EDGE_SLIDE_PS */)
     , (6626, 095 /* RADARBLIP_COLOR_INT */, 8 /* Yellow */)
     , (6626, 133 /* SHOWABLE_ON_RADAR_INT */, 4 /* ShowAlways_RadarEnum */)
     , (6626, 134 /* PLAYER_KILLER_STATUS_INT */, 16 /* RubberGlue_PKStatus */)
     , (6626, 146 /* XP_OVERRIDE_INT */, 3394);

INSERT INTO `weenie_properties_float` (`object_Id`, `type`, `value`)
VALUES (6626, 001 /* HEARTBEAT_INTERVAL_FLOAT */, 5)
     , (6626, 002 /* HEARTBEAT_TIMESTAMP_FLOAT */, 0)
     , (6626, 003 /* HEALTH_RATE_FLOAT */, 0.16)
     , (6626, 004 /* STAMINA_RATE_FLOAT */, 5)
     , (6626, 005 /* MANA_RATE_FLOAT */, 1)
     , (6626, 013 /* ARMOR_MOD_VS_SLASH_FLOAT */, 0.9)
     , (6626, 014 /* ARMOR_MOD_VS_PIERCE_FLOAT */, 1)
     , (6626, 015 /* ARMOR_MOD_VS_BLUDGEON_FLOAT */, 1.1)
     , (6626, 016 /* ARMOR_MOD_VS_COLD_FLOAT */, 0.4)
     , (6626, 017 /* ARMOR_MOD_VS_FIRE_FLOAT */, 0.4)
     , (6626, 018 /* ARMOR_MOD_VS_ACID_FLOAT */, 1)
     , (6626, 019 /* ARMOR_MOD_VS_ELECTRIC_FLOAT */, 0.6)
     , (6626, 054 /* USE_RADIUS_FLOAT */, 3)
     , (6626, 064 /* RESIST_SLASH_FLOAT */, 1)
     , (6626, 065 /* RESIST_PIERCE_FLOAT */, 1)
     , (6626, 066 /* RESIST_BLUDGEON_FLOAT */, 1)
     , (6626, 067 /* RESIST_FIRE_FLOAT */, 1)
     , (6626, 068 /* RESIST_COLD_FLOAT */, 1)
     , (6626, 069 /* RESIST_ACID_FLOAT */, 1)
     , (6626, 070 /* RESIST_ELECTRIC_FLOAT */, 1)
     , (6626, 071 /* RESIST_HEALTH_BOOST_FLOAT */, 1)
     , (6626, 072 /* RESIST_STAMINA_DRAIN_FLOAT */, 1)
     , (6626, 073 /* RESIST_STAMINA_BOOST_FLOAT */, 1)
     , (6626, 074 /* RESIST_MANA_DRAIN_FLOAT */, 1)
     , (6626, 075 /* RESIST_MANA_BOOST_FLOAT */, 1)
     , (6626, 104 /* OBVIOUS_RADAR_RANGE_FLOAT */, 10)
     , (6626, 125 /* RESIST_HEALTH_DRAIN_FLOAT */, 1);

INSERT INTO `weenie_properties_bool` (`object_Id`, `type`, `value`)
VALUES (6626, 001 /* STUCK_BOOL */, True)
     , (6626, 008 /* ALLOW_GIVE_BOOL */, True)
     , (6626, 012 /* REPORT_COLLISIONS_BOOL */, True)
     , (6626, 013 /* ETHEREAL_BOOL */, False)
     , (6626, 019 /* ATTACKABLE_BOOL */, False)
     , (6626, 041 /* REPORT_COLLISIONS_AS_ENVIRONMENT_BOOL */, True)
     , (6626, 042 /* ALLOW_EDGE_SLIDE_BOOL */, True)
     , (6626, 052 /* AI_IMMOBILE_BOOL */, True);

INSERT INTO `weenie_properties_attribute` (`object_Id`, `type`, `init_Level`, `level_From_C_P`, `c_P_Spent`)
VALUES (6626, 1, 220, 0, 0) /* STRENGTH_ATTRIBUTE */
     , (6626, 2, 200, 0, 0) /* ENDURANCE_ATTRIBUTE */
     , (6626, 3, 170, 0, 0) /* QUICKNESS_ATTRIBUTE */
     , (6626, 4, 220, 0, 0) /* COORDINATION_ATTRIBUTE */
     , (6626, 5, 150, 0, 0) /* FOCUS_ATTRIBUTE */
     , (6626, 6, 150, 0, 0) /* SELF_ATTRIBUTE */;

INSERT INTO `weenie_properties_attribute_2nd` (`object_Id`, `type`, `init_Level`, `level_From_C_P`, `c_P_Spent`, `current_Level`)
VALUES (6626, 1, 150, 0, 0, 250) /* MAX_HEALTH_ATTRIBUTE_2ND */
     , (6626, 3, 235, 0, 0, 435) /* MAX_STAMINA_ATTRIBUTE_2ND */
     , (6626, 5, 150, 0, 0, 300) /* MAX_MANA_ATTRIBUTE_2ND */;

INSERT INTO `weenie_properties_create_list` (`object_Id`, `destination_Type`, `weenie_Class_Id`, `stack_Size`, `palette`, `shade`, `try_To_Bond`)
VALUES (6626, 2, 130, 0, 2, 0.67, False) /* Create Shirt for Wield_DestinationType */
     , (6626, 2, 2604, 0, 9, 0, False) /* Create Breeches for Wield_DestinationType */
     , (6626, 2, 115, 0, 4, 0.8, False) /* Create Leather Boots for Wield_DestinationType */;

INSERT INTO `weenie_properties_body_part` (`object_Id`, `key`, `d_Type`, `d_Val`, `d_Var`, `base_Armor`, `armor_Vs_Slash`, `armor_Vs_Pierce`, `armor_Vs_Bludgeon`, `armor_Vs_Cold`, `armor_Vs_Fire`, `armor_Vs_Acid`, `armor_Vs_Electric`, `armor_Vs_Nether`, `b_h`, `h_l_f`, `m_l_f`, `l_l_f`, `h_r_f`, `m_r_f`, `l_r_f`, `h_l_b`, `m_l_b`, `l_l_b`, `h_r_b`, `m_r_b`, `l_r_b`)
VALUES (6626, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0.33, 0, 0, 0.33, 0, 0, 0.33, 0, 0, 0.33, 0, 0) /* HEAD */
     , (6626, 1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0.44, 0.17, 0, 0.44, 0.17, 0, 0.44, 0.17, 0, 0.44, 0.17, 0) /* CHEST */
     , (6626, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0.17, 0, 0, 0.17, 0, 0, 0.17, 0, 0, 0.17, 0) /* ABDOMEN */
     , (6626, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0.23, 0.03, 0, 0.23, 0.03, 0, 0.23, 0.03, 0, 0.23, 0.03, 0) /* UPPER_ARM */
     , (6626, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0.3, 0, 0, 0.3, 0, 0, 0.3, 0, 0, 0.3, 0) /* LOWER_ARM */
     , (6626, 5, 4, 2, 0.75, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0.2, 0, 0, 0.2, 0, 0, 0.2, 0, 0, 0.2, 0) /* HAND */
     , (6626, 6, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0.13, 0.18, 0, 0.13, 0.18, 0, 0.13, 0.18, 0, 0.13, 0.18) /* UPPER_LEG */
     , (6626, 7, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0.6, 0, 0, 0.6, 0, 0, 0.6, 0, 0, 0.6) /* LOWER_LEG */
     , (6626, 8, 4, 2, 0.75, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0.22, 0, 0, 0.22, 0, 0, 0.22, 0, 0, 0.22) /* FOOT */;

INSERT INTO `weenie_properties_skill` (`object_Id`, `type`, `level_From_P_P`, `s_a_c`, `p_p`, `init_Level`, `resistance_At_Last_Check`, `last_Used_Time`)
VALUES (6626, 6, 0, 2 /* TRAINED_SKILL_ADVANCEMENT_CLASS */, 0, 1, 0, 482.607505406773) /* MELEE_DEFENSE_SKILL */
     , (6626, 7, 0, 2 /* TRAINED_SKILL_ADVANCEMENT_CLASS */, 0, 1, 0, 482.607505406773) /* MISSILE_DEFENSE_SKILL */
     , (6626, 13, 0, 2 /* TRAINED_SKILL_ADVANCEMENT_CLASS */, 0, 1, 0, 482.607505406773) /* UNARMED_COMBAT_SKILL */;

INSERT INTO `weenie_properties_emote` (`object_Id`, `probability`, `category`, `emote_Set_Id`, `weenie_Class_Id`, `style`, `substyle`, `quest`, `vendor_Type`, `min_Health`, `max_Health`)
VALUES (6626, 1, 6 /* Give_EmoteCategory */, 0, 6620 /* Glimmering Gem */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 1, 6622 /* Sparkling Gem */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 2, 6621 /* Scintillating Gem */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 3, 6613 /* Lesser Koujia Shadow Leggings */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 4, 7725 /* Lesser Koujia Shadow Leggings */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 5, 6619 /* Lesser Koujia Shadow Sleeves */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 6, 7755 /* Lesser Koujia Shadow Sleeves */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 7, 6598 /* Lesser Koujia Shadow Breastplate */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 8, 7648 /* Lesser Koujia Shadow Breastplate */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 9, 6611 /* Koujia Shadow Leggings */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 10, 7730 /* Koujia Shadow Leggings */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 11, 6617 /* Koujia Shadow Sleeves */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 12, 7760 /* Koujia Shadow Sleeves */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 13, 6596 /* Koujia Shadow Breastplate */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 14, 7653 /* Koujia Shadow Breastplate */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 15, 14847 /* Greater Koujia Shadow Leggings */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 16, 7720 /* Greater Koujia Shadow Leggings */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 17, 14855 /* Greater Koujia Shadow Sleeves */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 18, 7750 /* Greater Koujia Shadow Sleeves */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 19, 14827 /* Greater Koujia Shadow Breastplate */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 20, 7643 /* Greater Koujia Shadow Breastplate */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 21, 14848 /* Greater Koujia Shadow Leggings */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 22, 14849 /* Greater Koujia Shadow Leggings */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 23, 14850 /* Greater Koujia Shadow Leggings */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 24, 14856 /* Greater Koujia Shadow Sleeves */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 25, 14857 /* Greater Koujia Shadow Sleeves */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 26, 14858 /* Greater Koujia Shadow Sleeves */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 27, 14828 /* Greater Koujia Shadow Breastplate */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 28, 14829 /* Greater Koujia Shadow Breastplate */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 29, 14830 /* Greater Koujia Shadow Breastplate */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 30, 6807 /* Nexus Core Gem */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 31, 8113 /* Fenmalain Gem */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 32, 8114 /* Fenmalain Soul Gem */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 33, 8111 /* Caulnalain Gem */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 34, 8112 /* Caulnalain Soul Gem */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 35, 8118 /* Shendolain Gem */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 6 /* Give_EmoteCategory */, 36, 8119 /* Shendolain Soul Gem */, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 7 /* Use_EmoteCategory */, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 1, 12 /* QuestSuccess_EmoteCategory */, 0, NULL, NULL, NULL, 'LesserShadowArmorSho1', NULL, NULL, NULL)
     , (6626, 1, 12 /* QuestSuccess_EmoteCategory */, 1, NULL, NULL, NULL, 'LesserShadowArmorSho2', NULL, NULL, NULL)
     , (6626, 1, 12 /* QuestSuccess_EmoteCategory */, 2, NULL, NULL, NULL, 'LesserShadowArmorSho3', NULL, NULL, NULL)
     , (6626, 1, 12 /* QuestSuccess_EmoteCategory */, 3, NULL, NULL, NULL, 'ShadowArmorSho1', NULL, NULL, NULL)
     , (6626, 1, 12 /* QuestSuccess_EmoteCategory */, 4, NULL, NULL, NULL, 'ShadowArmorSho2', NULL, NULL, NULL)
     , (6626, 1, 12 /* QuestSuccess_EmoteCategory */, 5, NULL, NULL, NULL, 'ShadowArmorSho3', NULL, NULL, NULL)
     , (6626, 1, 12 /* QuestSuccess_EmoteCategory */, 6, NULL, NULL, NULL, 'GreaterShadowArmorSho1', NULL, NULL, NULL)
     , (6626, 1, 12 /* QuestSuccess_EmoteCategory */, 7, NULL, NULL, NULL, 'GreaterShadowArmorSho2', NULL, NULL, NULL)
     , (6626, 1, 12 /* QuestSuccess_EmoteCategory */, 8, NULL, NULL, NULL, 'GreaterShadowArmorSho3', NULL, NULL, NULL)
     , (6626, 1, 13 /* QuestFailure_EmoteCategory */, 0, NULL, NULL, NULL, 'LesserShadowArmorSho1', NULL, NULL, NULL)
     , (6626, 1, 13 /* QuestFailure_EmoteCategory */, 1, NULL, NULL, NULL, 'LesserShadowArmorSho2', NULL, NULL, NULL)
     , (6626, 1, 13 /* QuestFailure_EmoteCategory */, 2, NULL, NULL, NULL, 'LesserShadowArmorSho3', NULL, NULL, NULL)
     , (6626, 1, 13 /* QuestFailure_EmoteCategory */, 3, NULL, NULL, NULL, 'ShadowArmorSho1', NULL, NULL, NULL)
     , (6626, 1, 13 /* QuestFailure_EmoteCategory */, 4, NULL, NULL, NULL, 'ShadowArmorSho2', NULL, NULL, NULL)
     , (6626, 1, 13 /* QuestFailure_EmoteCategory */, 5, NULL, NULL, NULL, 'ShadowArmorSho3', NULL, NULL, NULL)
     , (6626, 1, 13 /* QuestFailure_EmoteCategory */, 6, NULL, NULL, NULL, 'GreaterShadowArmorSho1', NULL, NULL, NULL)
     , (6626, 1, 13 /* QuestFailure_EmoteCategory */, 7, NULL, NULL, NULL, 'GreaterShadowArmorSho2', NULL, NULL, NULL)
     , (6626, 1, 13 /* QuestFailure_EmoteCategory */, 8, NULL, NULL, NULL, 'GreaterShadowArmorSho3', NULL, NULL, NULL);

INSERT INTO `weenie_properties_emote_action` (`object_Id`, `emote_Category`, `emote_Set_Id`, `order`, `type`, `delay`, `extent`, `motion`, `message`, `test_String`, `min`, `max`, `min_64`, `max_64`, `min_Dbl`, `max_Dbl`, `stat`, `display`, `amount`, `amount_64`, `hero_X_P_64`, `percent`, `spell_Id`, `wealth_Rating`, `treasure_Class`, `treasure_Type`, `p_Script`, `sound`, `destination_Type`, `weenie_Class_Id`, `stack_Size`, `palette`, `shade`, `try_To_Bond`, `obj_Cell_Id`, `origin_X`, `origin_Y`, `origin_Z`, `angles_W`, `angles_X`, `angles_Y`, `angles_Z`)
VALUES (6626, 6 /* Give_EmoteCategory */, 0, 0, 20 /* UpdateQuest_EmoteType */, 0, 1, NULL, 'LesserShadowArmorSho1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 1, 0, 20 /* UpdateQuest_EmoteType */, 0, 1, NULL, 'ShadowArmorSho1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 2, 0, 20 /* UpdateQuest_EmoteType */, 0, 1, NULL, 'GreaterShadowArmorSho1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 3, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 3, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 7725 /* Lesser Koujia Shadow Leggings */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 4, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 4, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6613 /* Lesser Koujia Shadow Leggings */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 5, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 5, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 7755 /* Lesser Koujia Shadow Sleeves */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 6, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 6, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6619 /* Lesser Koujia Shadow Sleeves */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 7, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 7, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 7648 /* Lesser Koujia Shadow Breastplate */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 8, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 8, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6598 /* Lesser Koujia Shadow Breastplate */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 9, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 9, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 7730 /* Koujia Shadow Leggings */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 10, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 10, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6611 /* Koujia Shadow Leggings */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 11, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 11, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 7760 /* Koujia Shadow Sleeves */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 12, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 12, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6617 /* Koujia Shadow Sleeves */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 13, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 13, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 7653 /* Koujia Shadow Breastplate */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 14, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 14, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6596 /* Koujia Shadow Breastplate */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 15, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 15, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 7720 /* Greater Koujia Shadow Leggings */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 16, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 16, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 14847 /* Greater Koujia Shadow Leggings */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 17, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 17, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 7750 /* Greater Koujia Shadow Sleeves */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 18, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 18, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 14855 /* Greater Koujia Shadow Sleeves */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 19, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 19, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 7643 /* Greater Koujia Shadow Breastplate */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 20, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 20, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 14827 /* Greater Koujia Shadow Breastplate */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 21, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 21, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 14847 /* Greater Koujia Shadow Leggings */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 22, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 22, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 14847 /* Greater Koujia Shadow Leggings */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 23, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 23, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 14847 /* Greater Koujia Shadow Leggings */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 24, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 24, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 14855 /* Greater Koujia Shadow Sleeves */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 25, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 25, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 14855 /* Greater Koujia Shadow Sleeves */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 26, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 26, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 14855 /* Greater Koujia Shadow Sleeves */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 27, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 27, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 14827 /* Greater Koujia Shadow Breastplate */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 28, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 28, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 14827 /* Greater Koujia Shadow Breastplate */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 29, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here you are.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 29, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 14827 /* Greater Koujia Shadow Breastplate */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 30, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Breathtaking... I have never heard of a crystal of this size and power. You must be the one who dealt the killing blow to the great Nexus Crystal! I will make you a full suit of Koujia armor that surpasses all my previous work.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 30, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6798 /* Nexus Koujia Breastplate */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 30, 2, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6805 /* Nexus Koujia Sleeves */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 30, 3, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6803 /* Nexus Koujia Leggings */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 31, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Ayeeyah! This gem would be beyond my skill even if I were not suffering the curse of the shadow assassin! Try those three arrogant collectors near Uziz, I think they wanted gems like this.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 31, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 8113 /* Fenmalain Gem */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 32, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Ayeeyah! This gem would be beyond my skill even if I were not suffering the curse of the shadow assassin! Try those three arrogant collectors near Uziz, I think they wanted gems like this.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 32, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 8114 /* Fenmalain Soul Gem */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 33, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Ayeeyah! This gem would be beyond my skill even if I were not suffering the curse of the shadow assassin! Try those three arrogant collectors near Uziz, I think they wanted gems like this.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 33, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 8111 /* Caulnalain Gem */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 34, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Ayeeyah! This gem would be beyond my skill even if I were not suffering the curse of the shadow assassin! Try those three arrogant collectors near Uziz, I think they wanted gems like this.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 34, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 8112 /* Caulnalain Soul Gem */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 35, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Ayeeyah! This gem would be beyond my skill even if I were not suffering the curse of the shadow assassin! Try those three arrogant collectors near Uziz, I think they wanted gems like this.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 35, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 8118 /* Shendolain Gem */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 36, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Ayeeyah! This gem would be beyond my skill even if I were not suffering the curse of the shadow assassin! Try those three arrogant collectors near Uziz, I think they wanted gems like this.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 6 /* Give_EmoteCategory */, 36, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 8119 /* Shendolain Soul Gem */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 7 /* Use_EmoteCategory */, 0, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Nuhmudira has finally restored us to full health!  She has also stocked us with some extra supplies that we needed, such that we can provide you with either a version of the original Shadow Armor, or its successor.  If you wish to trade one version of your Koujia set for another, simply hand it to me.  Please take out all Atlan stones from your armor before handing it to me.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 7 /* Use_EmoteCategory */, 0, 1, 10 /* Tell_EmoteType */, 1, 1, NULL, 'Also, if you wish to color your new Greater Shadow Armor, you may buy a vat of color from my assistant.  If you do not like the color, please give me the armor piece and I will replace it with the standard piece, which you may then choose to recolor.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 0, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'A small gem... I salute your accomplishment. Here is a set of Koujia leggings, infused with the power of the gem. With another gem of similar quality I can make a breastplate and sleeves to match.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 0, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6613 /* Lesser Koujia Shadow Leggings */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 1, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'This gem allows me to complete your suit of armor. Take this breastplate and these sleeves, with my compliments.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 1, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6598 /* Lesser Koujia Shadow Breastplate */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 1, 2, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6619 /* Lesser Koujia Shadow Sleeves */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 2, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'I cannot do anything more for you with these smaller gems. Please take this back.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 2, 1, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'LesserShadowArmorSho1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 2, 2, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'LesserShadowArmorSho2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 2, 3, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'LesserShadowArmorSho3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 2, 4, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6620 /* Glimmering Gem */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 2, 5, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Unless ... If you want another suit of this inferior armor, give this gem back to me and I''ll see what I can do.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 3, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Admirable. A potent gem. Here are some fine Koujia leggings for you. Another gem like that will allow me to craft sleeves and a breastplate for you.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 3, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6611 /* Koujia Shadow Leggings */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 4, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'A fine accomplishment, to make this gem. Here are the sleeves and breastplate I promised you.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 4, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6596 /* Koujia Shadow Breastplate */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 4, 2, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6617 /* Koujia Shadow Sleeves */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 5, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'I have done the best I can with the materials provided.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 5, 1, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'ShadowArmorSho1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 5, 2, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'ShadowArmorSho2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 5, 3, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'ShadowArmorSho3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 5, 4, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6622 /* Sparkling Gem */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 5, 5, 10 /* Tell_EmoteType */, 0, 1, NULL, 'If you want another suit of this quality, give this gem back to me and I''ll see what I can do.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 6, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'A gem of the best quality!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 6, 1, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Here are your leggings. With another great gem such as this, I could make you similar upper-body armor.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 6, 2, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 14847 /* Greater Koujia Shadow Leggings */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 7, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Impressive! Here is the upper-body armor I promised you. It is an honor to craft for a warrior of your prowess.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 7, 1, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 14855 /* Greater Koujia Shadow Sleeves */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 7, 2, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 14827 /* Greater Koujia Shadow Breastplate */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 8, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Regrettably I have reached the limits of my craft, and I cannot spare any more time to make you armor. Here is your gem back.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 8, 1, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'GreaterShadowArmorSho1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 8, 2, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'GreaterShadowArmorSho2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 8, 3, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'GreaterShadowArmorSho3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 8, 4, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6621 /* Scintillating Gem */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 12 /* QuestSuccess_EmoteCategory */, 8, 5, 10 /* Tell_EmoteType */, 0, 1, NULL, 'If you *insist* on another suit of this quality, give this gem back to me and I''ll see what I can do.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 0, 0, 20 /* UpdateQuest_EmoteType */, 0, 1, NULL, 'LesserShadowArmorSho2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 1, 0, 20 /* UpdateQuest_EmoteType */, 0, 1, NULL, 'LesserShadowArmorSho3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 2, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'I cannot do anything more for you with these smaller gems. Please take this back.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 2, 1, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'LesserShadowArmorSho1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 2, 2, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'LesserShadowArmorSho2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 2, 3, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'LesserShadowArmorSho3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 2, 4, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6620 /* Glimmering Gem */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 2, 5, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Unless ... If you want another suit of this inferior armor, give this gem back to me and I''ll see what I can do.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 3, 0, 20 /* UpdateQuest_EmoteType */, 0, 1, NULL, 'ShadowArmorSho2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 4, 0, 20 /* UpdateQuest_EmoteType */, 0, 1, NULL, 'ShadowArmorSho3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 5, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'I have done the best I can with the materials provided.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 5, 1, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'ShadowArmorSho1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 5, 2, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'ShadowArmorSho2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 5, 3, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'ShadowArmorSho3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 5, 4, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6622 /* Sparkling Gem */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 5, 5, 10 /* Tell_EmoteType */, 0, 1, NULL, 'If you want another suit of this quality, give this gem back to me and I''ll see what I can do.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 6, 0, 20 /* UpdateQuest_EmoteType */, 0, 1, NULL, 'GreaterShadowArmorSho2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 7, 0, 20 /* UpdateQuest_EmoteType */, 0, 1, NULL, 'GreaterShadowArmorSho3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 8, 0, 10 /* Tell_EmoteType */, 0, 1, NULL, 'Regrettably I have reached the limits of my craft, and I cannot spare any more time to make you armor. Here is your gem back.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 8, 1, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'GreaterShadowArmorSho1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 8, 2, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'GreaterShadowArmorSho2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 8, 3, 31 /* EraseQuest_EmoteType */, 0, 1, NULL, 'GreaterShadowArmorSho3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 8, 4, 3 /* Give_EmoteType */, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6621 /* Scintillating Gem */, 1, 0, 0, False, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (6626, 13 /* QuestFailure_EmoteCategory */, 8, 5, 10 /* Tell_EmoteType */, 0, 1, NULL, 'If you *insist* on another suit of this quality, give this gem back to me and I''ll see what I can do.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

